export {default as Home} from './Home'
export {default as About} from './About'
export {default as Chat} from './Chat'
export {default as Transcription} from './Transcription'
export {default as ShopPage} from './Shop'