export {default as Home} from './Home'
export {default as TravelBot} from './TravelBot'
export {default as Chat} from './Chat'
export {default as Transcription} from './Transcription'
export {default as ShopPage} from './Shop'
export {default as VideoPage} from './Video'